[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AddTorrentStopped=false
Session\AdditionalTrackers=udp://tracker.opentrackr.org:1337/announce\n\nudp://open.demonii.com:1337/announce\n\nudp://open.stealth.si:80/announce\n\nudp://tracker.torrent.eu.org:451/announce\n\nudp://tracker.srv00.com:6969/announce\n\nudp://tracker.qu.ax:6969/announce\n\nudp://tracker.coppersurfer.tk:6969/announce\n\nudp://tracker.leechers-paradise.org:6969/announce\n\nudp://explodie.org:6969/announce\n\nudp://tracker.tiny-vps.com:6969/announce\n\nudp://tracker.openbittorrent.com:80/announce\n\nudp://tracker.cyberia.is:6969/announce\n\nudp://ipv4.tracker.harry.lu:80/announce\n\nudp://exodus.desync.com:6969/announce\n\nudp://tracker.moack.co.kr:80/announce\n\nudp://opentracker.i2p.rocks:6969/announce\n\nudp://tracker.zerobytes.to:1337/announce\n\nudp://tracker.1337x.to:80/announce
Session\AdditionalTrackersEnabled=true
Session\AnnounceToAllTrackers=true
Session\DHTEnabled=true
Session\DefaultSavePath=/downloads/
Session\Encryption=0
Session\LSDEnabled=true
Session\MaxConnections=500
Session\MaxConnectionsPerTorrent=150
Session\MaxUploads=100
Session\MaxUploadsPerTorrent=20
Session\PexEnabled=true
Session\Port=60881
Session\QueueingSystemEnabled=true
Session\SSL\Port=10285
Session\ShareLimitAction=Stop
Session\TempPath=/downloads/incomplete/

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()
PortForwardingEnabled=true
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\GlobalUPLimit=1000
Connection\PortRangeMin=60881
Connection\UPnP=true
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
WebUI\Address=*
WebUI\AuthSubnetWhitelist=10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\Enabled=true
WebUI\LocalHostAuth=false
WebUI\Port=8080
WebUI\ServerDomains=*
